# This memorystore file represent any instance of memorystore that can be connected and used in any plugin of Altair
# This config is environment agnostic, so it can be used in any environment based on it's environment variables.
# This is the sample of memorystore config:
# <memorystore_name>: string                  - The memorystore instance name
#   <example>
#   driver: string                            - Memorystore driver used, required. Available: memcached

main_memorystore:
  driver: memcached
  instance:
    - host: localhost
      port: 11211

