name: General workflows

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19

      - uses: actions/checkout@v2

      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: Go mod vendor
        run: go mod vendor

      - name: Lint
        run: make lint

      - name: Unit Test
        run: make test

      - name: Upload coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=cover.out -service=github
